stages:
   - buildResumeGeneratorServer

#TODO add vue build stage

language: java

jdk:
  openjdk11

buildResumeGeneratorServer:
  stage: buildResumeGeneratorServer
  before_script:
    cd ./resume-generator-server
  script:
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)