stages:
   - buildResumeGeneratorServer
#TODO add vue build stage

lanauage: java

jdk:
  openjdk11

buildResumeGeneratorServer:
  stage: buildResumeGeneratorServer
  script:
    cd ./resume-generator-server
  install:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)